#!/bin/bash
ariacore() {
    okay=0
    while [ 1 ]
    do
	rosrun aria_utils aria get_exist
	okay=$(rosrun aria_utils aria get_exist ret)
	if [ "$(echo $okay)" == "20 ---" ]; then
	    echo "exist ok"
	    break
	else
	    echo -e "\e[1;31m$okay done with errors\e[m"
	fi
    done
    okay=0
    while [ 1 ]
    do
	rosrun aria_utils aria apply_gain
	okay=$(rosrun aria_utils aria apply_gain ret)
	if [ "$(echo $okay)" == "20 ---" ]; then
	    echo "gain ok"
	    break
	else
	    echo -e "\e[1;31m$okay done with errors\e[m"
	fi
    done
    okay=0
    while [ 1 ]
    do
	rosrun aria_utils aria initiate
	okay=$(rosrun aria_utils aria initiate ret)
	if [ "$(echo $okay)" == "20 ---" ]; then
	    echo "initate ok"
	    break
	else
	    echo -e "\e[1;31m$okay done with errors\e[m"
	fi
    done
}

ariacore