#!/bin/bash
template() {
  linear=1.0
  bezier=2.0
  slowout=3.0
  slowin=4.0
  sigmoid=5.0
  cubic=6.0

  gt=1.5
  gt1=0.3
  gte=0.5

  rosrun aria_utils aria pub setInterpolation $sigmoid
  rosrun aria_utils aria pub eye [0.8,0.8,$gt1] &
  rosrun aria_utils aria pub position [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.12566371262073517,0.0,0.0,0.08377580344676971,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,$gt] &
  sleep $gt1; rosrun aria_utils aria pub eye [-0.8,0.6,$gt1] &
  sleep $gt1; rosrun aria_utils aria pub eye [-0.6,-0.8,$gt1] &
  sleep $gt1; rosrun aria_utils aria pub eye [0.8,-0.6,$gt1] &
  sleep $gt1; rosrun aria_utils aria pub eye [0.6,0.8,$gt1] &
  rosrun aria_utils aria pub position [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.12566371262073517,0.0,0.0,-0.08377580344676971,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,$gt] &
  sleep $gt1; rosrun aria_utils aria pub eye [-0.8,0.6,$gt1] &
  sleep $gt1; rosrun aria_utils aria pub eye [-0.6,-0.8,$gt1] &
  sleep $gt1; rosrun aria_utils aria pub eye [0.8,-0.6,$gt1] &
  sleep $gt1; rosrun aria_utils aria pub eye [0.0,0.0,$gt1] &
  rosrun aria_utils aria pub position [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,$gte] &
  sleep $gt
}

template