#!/bin/bash
template() {
  linear=1.0
  bezier=2.0
  slowout=3.0
  slowin=4.0
  sigmoid=5.0
  cubic=6.0

  gt=1.0

  rosrun aria_utils aria pub setInterpolation $linear
  rosrun aria_utils aria pub position [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,$gt] &
  rosrun aria_utils aria pub gripper [1.0,1.0,$gt] &
  rosrun aria_utils aria pub eye [0.0,0.0,$gt]

  sleep $gt
}

template